project_name: 'GEMPAK User Manual'
github_user: Unidata
github_project: gempak
baseurl: /gempak

markdown: kramdown
highlighter: true
lsi: false
safe: false
add_permalinks: true # adds permalinks to heading tags.

exclude: ["node_modules", "sass", "README.md",
          "Gruntfile.js", "package.json", "config.rb", "bower.json",
          "Gemfile", "Gemfile.lock", "deploy.sh"]

kramdown:
  toc_levels: 1..3
